name: Build NoCheatPlus

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin

      - name: Build NoCheatPlus
        run: mvn clean package -P nonfree_build -P all

      - name: Get the date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d')"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.date.outputs.date }}-Snow-Motd
          path: target/*.jar
